# Site settings
title: P4
email: p4@p4.org
author: The P4 Language Consirtum

url: "https://p4lang.github.io/web/"
baseurl: "/web"

social:
  - title: twitter
    url: https://twitter.com/p4lang
  - title: github
    url: http://github.com/p4lang

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json"]

gems: [jekyll-paginate, jekyll-feed]
