# Site settings
title: P4
email: p4@p4.org
description: The P4 Language Consirtum

baseurl: "/web/"
url: "https://p4lang.github.io" 

data-ad-slot: ""
data-ad-client: ""
google_ad_client: ""

google_analytics: ""
addthis_id: ""

social:
  - title: twitter
    url: https://twitter.com/p4lang
  - title: github
    url: http://github.com/p4lang

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
